name: TY_pan-daily-task

on: 
  push:
  schedule:
    - cron: 42 3 * * *

jobs:
  run-TY_pan-tool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      - name: Working
        env:
          PUSHSCKEY: ${{secrets.PUSHSCKEY}}
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: 
          python ./code/TY_pan.py