name: main test

on: 
  push：
  workflow_dispatch:
  schedule:
    - cron: '50 30 * * *'

jobs:
  TY_pan-daily:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      - name: Working
        env:
          PUSHSCKEY: ${{secrets.PUSHSCKEY}}
        run: 
          python ./code/TY_pan.py