name: 天翼云盘签到

on: 
  workflow_dispatch:
  schedule:
    - cron: '22 22 * * *'       

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: production_environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
      
      - name: Working
        env:
          CORPID: ${{secrets.CORPID}}
          AGENTID: ${{secrets.AGENTID}}
          CORPSECRET: ${{secrets.CORPSECRET}}
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: 
          python ./code/TY_pan.py